url:
#    shares: https://www.brvm.org/en/cours-actions/0
    shares: https://www.sikafinance.com/marches/aaz
    bonds: https://www.brvm.org/en/cours-obligations/0
    capitalizations: https://www.brvm.org/en/capitalisations/0
    volumes: https://www.brvm.org/en/volumes/0
    indices: https://www.brvm.org/en/indices
    dividends: https://www.richbourse.com/common/dividende/index
data:
    path: data/

gcp:
#    project_id:  prd-tradvisor
    gcs:
        bucket: data-brvm
        archive: archive-brvm
    bigquery:
        dataset: stocks

duckdb:
    database: database/financial_assets.db


csv_directory: /Users/issacamara/Developer/tradvisor/data/
archive: processed_data/
