name: Deploy to Cloud Run

on:
  push:
    branches:
      - main   # change if you want another branch to trigger deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD_TOKEN }}

      # Build and push Docker image to Docker Hub
      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/tradvisor
          IMAGE_TAG=latest
          docker build -t $IMAGE_NAME:$IMAGE_TAG . --platform linux/amd64
          docker push $IMAGE_NAME:$IMAGE_TAG

      # Set up GCP authentication
      - name: Set up GCP credentials
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Set up gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/tradvisor:latest
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE }} \
            --image $IMAGE_NAME \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated